apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    meadata:
      labels:
        component: worker
    spec:
      conatiner:
        - name: worker
          image: orkhanhuseynli/multi-worker
